version: "3.9"
services:
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Identity_Development_2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
        - db
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic
    depends_on:
      - db
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch 
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic
  identity:
    container_name: identity
    image: identity
    ports:
      - "8080:8080"
    depends_on:
      - kibana
    environment:
      - TEST_ConnectionString=13
    networks:
      - db
networks:
  elastic:
    driver: bridge
  db:
    driver: bridge
volumes:
  elasticsearch-data: