version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Identity_Development_2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

